#define KYTY_VERSION "0.2.2"
#define KYTY_ENDIAN KYTY_ENDIAN_LITTLE
#define KYTY_PLATFORM KYTY_PLATFORM_WINDOWS
#define KYTY_COMPILER KYTY_COMPILER_CLANG
#define KYTY_LINKER KYTY_LINKER_LLD_LINK
#define KYTY_BUILD KYTY_BUILD_RELEASE
/* #undef KYTY_FINAL */

