# CMake generated Testfile for 
# Source directory: C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src
# Build directory: C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("image_page_table" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/image_page_table_tests.exe")
set_tests_properties("image_page_table" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;453;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("memory_tracker" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/memory_tracker_tests.exe")
set_tests_properties("memory_tracker" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;454;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("page_manager" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/page_manager_tests.exe")
set_tests_properties("page_manager" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;455;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("pipeline_cache_data" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/pipeline_cache_data_tests.exe")
set_tests_properties("pipeline_cache_data" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;456;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("graphics_audio_semantics" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/graphics_audio_semantics_tests.exe")
set_tests_properties("graphics_audio_semantics" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;457;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("pm4_ngs2_fuzz" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/pm4_ngs2_fuzz_tests.exe" "--iterations=4096")
set_tests_properties("pm4_ngs2_fuzz" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;458;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("soft_ignore_evidence" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/soft_ignore_evidence_tests.exe")
set_tests_properties("soft_ignore_evidence" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;459;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("resource_mutex" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/resource_mutex_tests.exe")
set_tests_properties("resource_mutex" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;460;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("event_queue_lifetime" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/event_queue_lifetime_tests.exe")
set_tests_properties("event_queue_lifetime" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;461;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("shader_recompiler_compute" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe")
set_tests_properties("shader_recompiler_compute" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;462;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("command_scheduler_timeline" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--scheduler-only")
set_tests_properties("command_scheduler_timeline" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;463;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("stream_buffer_ring" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--stream-buffer-only")
set_tests_properties("stream_buffer_ring" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;465;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("gpu_command_lane" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--gpu-command-lane-only")
set_tests_properties("gpu_command_lane" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;467;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("gpu_tiler" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--gpu-tiler-only")
set_tests_properties("gpu_tiler" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;469;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("texture_cache_layered_image" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--layered-image-only")
set_tests_properties("texture_cache_layered_image" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;472;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("texture_cache_image_views" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--image-view-cache-only")
set_tests_properties("texture_cache_image_views" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;474;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("texture_cache_storage_sampled" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--storage-sampled-only")
set_tests_properties("texture_cache_storage_sampled" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;476;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("texture_cache_depth_readback" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--depth-readback-only")
set_tests_properties("texture_cache_depth_readback" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;478;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("buffer_cache_dirty_gc" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--buffer-cache-gc-only")
set_tests_properties("buffer_cache_dirty_gc" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;480;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("texture_cache_image_overlap" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--image-overlap-only")
set_tests_properties("texture_cache_image_overlap" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;485;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("texture_cache_htile_clear" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--htile-clear-only")
set_tests_properties("texture_cache_htile_clear" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;487;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
add_test("buffer_cache_ranges" "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/_BuildLauncher/shader_recompiler_compute_tests.exe" "--buffer-cache-range-only")
set_tests_properties("buffer_cache_ranges" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;489;add_test;C:/Users/Keshav/Desktop/Ps5Emu/KytyPS5/src/CMakeLists.txt;0;")
subdirs("3rdparty")
subdirs("common")
subdirs("launcher")
