// SPDX-FileCopyrightText: Copyright 2024 KytyPlus
// SPDX-License-Identifier: MIT
//
// FSR-inspired spatial upscaler: EASU + RCAS two-pass compute pipeline.

#include "graphics/presentation/fsrUpscaler.h"

#include "common/assert.h"
#include "graphics/host_gpu/graphicContext.h"

// Embedded SPIR-V shaders (generated by CMake from .comp sources).
#include "fsr_shaders/fsr_easu_spv.h"
#include "fsr_shaders/fsr_rcas_spv.h"

namespace Libs::Graphics {

// UBO layout matching the GLSL std140 blocks.
struct EasuUbo {
	float src_size[2];
	float dst_size[2];
	float src_pixel[2];
	float dst_pixel[2];
	float scale[2];
	float pad0[2];
};

struct RcasUbo {
	float src_size[2];
	float src_pixel[2];
	float sharpness;
	float pad0;
	float pad1;
	float pad2;
};

FsrUpscaler::~FsrUpscaler() {
	Destroy();
}

bool FsrUpscaler::Create(GraphicContext& gfx) {
	m_gfx = &gfx;

	// Sampler: linear filtering, clamp-to-edge.
	vk::SamplerCreateInfo sampler_info {};
	sampler_info.magFilter    = vk::Filter::eLinear;
	sampler_info.minFilter    = vk::Filter::eLinear;
	sampler_info.mipmapMode   = vk::SamplerMipmapMode::eNearest;
	sampler_info.addressModeU = vk::SamplerAddressMode::eClampToEdge;
	sampler_info.addressModeV = vk::SamplerAddressMode::eClampToEdge;
	sampler_info.addressModeW = vk::SamplerAddressMode::eClampToEdge;
	sampler_info.maxLod       = 0.0f;
	auto result = gfx.device.createSampler(&sampler_info, nullptr, &m_linear_sampler);
	if (result != vk::Result::eSuccess) {
		LOGF("FsrUpscaler: failed to create sampler\n");
		return false;
	}

	if (!CreatePipelines()) return false;
	if (!CreateDescriptorResources()) return false;

	m_ready = true;
	LOGF("FsrUpscaler: initialised (EASU + RCAS compute pipelines ready)\n");
	return true;
}

void FsrUpscaler::Destroy() {
	if (m_gfx == nullptr) return;
	auto dev = m_gfx->device;

	if (m_intermediate.image != nullptr) {
		if (m_intermediate.view != nullptr) dev.destroyImageView(m_intermediate.view, nullptr);
		dev.destroyImage(m_intermediate.image, nullptr);
		dev.freeMemory(m_intermediate.memory, nullptr);
		m_intermediate = {};
	}
	if (m_easu_ubo != nullptr) {
		dev.destroyBuffer(m_easu_ubo, nullptr);
		dev.freeMemory(m_easu_ubo_mem, nullptr);
		m_easu_ubo = nullptr;
	}
	if (m_rcas_ubo != nullptr) {
		dev.destroyBuffer(m_rcas_ubo, nullptr);
		dev.freeMemory(m_rcas_ubo_mem, nullptr);
		m_rcas_ubo = nullptr;
	}
	if (m_desc_pool != nullptr) {
		dev.destroyDescriptorPool(m_desc_pool, nullptr);
		m_desc_pool = nullptr;
	}
	if (m_easu_pipeline != nullptr) { dev.destroyPipeline(m_easu_pipeline, nullptr); m_easu_pipeline = nullptr; }
	if (m_rcas_pipeline != nullptr) { dev.destroyPipeline(m_rcas_pipeline, nullptr); m_rcas_pipeline = nullptr; }
	if (m_pipeline_layout != nullptr) { dev.destroyPipelineLayout(m_pipeline_layout, nullptr); m_pipeline_layout = nullptr; }
	if (m_ds_layout != nullptr) { dev.destroyDescriptorSetLayout(m_ds_layout, nullptr); m_ds_layout = nullptr; }
	if (m_linear_sampler != nullptr) { dev.destroySampler(m_linear_sampler, nullptr); m_linear_sampler = nullptr; }
	m_gfx   = nullptr;
	m_ready = false;
}

bool FsrUpscaler::CreatePipelines() {
	auto dev = m_gfx->device;

	// Descriptor set layout: 3 bindings (sampler, storage image, UBO).
	std::array<vk::DescriptorSetLayoutBinding, 3> bindings {};
	bindings[0].binding            = 0;
	bindings[0].descriptorType     = vk::DescriptorType::eCombinedImageSampler;
	bindings[0].descriptorCount    = 1;
	bindings[0].stageFlags         = vk::ShaderStageFlagBits::eCompute;
	bindings[1].binding            = 1;
	bindings[1].descriptorType     = vk::DescriptorType::eStorageImage;
	bindings[1].descriptorCount    = 1;
	bindings[1].stageFlags         = vk::ShaderStageFlagBits::eCompute;
	bindings[2].binding            = 2;
	bindings[2].descriptorType     = vk::DescriptorType::eUniformBuffer;
	bindings[2].descriptorCount    = 1;
	bindings[2].stageFlags         = vk::ShaderStageFlagBits::eCompute;

	vk::DescriptorSetLayoutCreateInfo ds_layout_info {};
	ds_layout_info.bindingCount = static_cast<uint32_t>(bindings.size());
	ds_layout_info.pBindings    = bindings.data();
	auto result = dev.createDescriptorSetLayout(&ds_layout_info, nullptr, &m_ds_layout);
	if (result != vk::Result::eSuccess) return false;

	// Pipeline layout.
	vk::PipelineLayoutCreateInfo pl_info {};
	pl_info.setLayoutCount = 1;
	pl_info.pSetLayouts    = &m_ds_layout;
	result = dev.createPipelineLayout(&pl_info, nullptr, &m_pipeline_layout);
	if (result != vk::Result::eSuccess) return false;

	// EASU compute pipeline.
	{
		vk::ShaderModuleCreateInfo sm_info {};
		sm_info.codeSize = sizeof(FSR_EASU_SPV);
		sm_info.pCode    = FSR_EASU_SPV;
		vk::ShaderModule module;
		result = dev.createShaderModule(&sm_info, nullptr, &module);
		if (result != vk::Result::eSuccess) return false;

		vk::PipelineShaderStageCreateInfo stage {};
		stage.stage  = vk::ShaderStageFlagBits::eCompute;
		stage.module = module;
		stage.pName  = "main";

		vk::ComputePipelineCreateInfo cp {};
		cp.stage  = stage;
		cp.layout = m_pipeline_layout;
		result = dev.createComputePipelines(nullptr, 1, &cp, nullptr, &m_easu_pipeline);
		dev.destroyShaderModule(module, nullptr);
		if (result != vk::Result::eSuccess) return false;
	}

	// RCAS compute pipeline.
	{
		vk::ShaderModuleCreateInfo sm_info {};
		sm_info.codeSize = sizeof(FSR_RCAS_SPV);
		sm_info.pCode    = FSR_RCAS_SPV;
		vk::ShaderModule module;
		result = dev.createShaderModule(&sm_info, nullptr, &module);
		if (result != vk::Result::eSuccess) return false;

		vk::PipelineShaderStageCreateInfo stage {};
		stage.stage  = vk::ShaderStageFlagBits::eCompute;
		stage.module = module;
		stage.pName  = "main";

		vk::ComputePipelineCreateInfo cp {};
		cp.stage  = stage;
		cp.layout = m_pipeline_layout;
		result = dev.createComputePipelines(nullptr, 1, &cp, nullptr, &m_rcas_pipeline);
		dev.destroyShaderModule(module, nullptr);
		if (result != vk::Result::eSuccess) return false;
	}

	return true;
}

bool FsrUpscaler::CreateDescriptorResources() {
	auto dev = m_gfx->device;

	// Descriptor pool: 2 sets, each with 1 sampler + 1 storage image + 1 UBO.
	std::array<vk::DescriptorPoolSize, 3> pool_sizes {};
	pool_sizes[0].type            = vk::DescriptorType::eCombinedImageSampler;
	pool_sizes[0].descriptorCount = 2;
	pool_sizes[1].type            = vk::DescriptorType::eStorageImage;
	pool_sizes[1].descriptorCount = 2;
	pool_sizes[2].type            = vk::DescriptorType::eUniformBuffer;
	pool_sizes[2].descriptorCount = 2;

	vk::DescriptorPoolCreateInfo pool_info {};
	pool_info.maxSets       = 2;
	pool_info.poolSizeCount = static_cast<uint32_t>(pool_sizes.size());
	pool_info.pPoolSizes    = pool_sizes.data();
	auto result = dev.createDescriptorPool(&pool_info, nullptr, &m_desc_pool);
	if (result != vk::Result::eSuccess) return false;

	// Allocate two descriptor sets.
	vk::DescriptorSetAllocateInfo alloc_info {};
	alloc_info.descriptorPool     = m_desc_pool;
	alloc_info.descriptorSetCount = 1;
	alloc_info.pSetLayouts        = &m_ds_layout;
	result = dev.allocateDescriptorSets(&alloc_info, &m_easu_ds);
	if (result != vk::Result::eSuccess) return false;
	result = dev.allocateDescriptorSets(&alloc_info, &m_rcas_ds);
	if (result != vk::Result::eSuccess) return false;

	// Create UBOs (EASU and RCAS share the same layout size for simplicity).
	constexpr vk::DeviceSize ubo_size = 64; // padded to 64 bytes, both UBOs fit.
	for (auto* buf_ptr: {&m_easu_ubo, &m_rcas_ubo}) {
		vk::BufferCreateInfo buf_info {};
		buf_info.size        = ubo_size;
		buf_info.usage       = vk::BufferUsageFlagBits::eUniformBuffer;
		buf_info.sharingMode = vk::SharingMode::eExclusive;
		result = dev.createBuffer(&buf_info, nullptr, buf_ptr);
		if (result != vk::Result::eSuccess) return false;
	}

	// Allocate host-visible memory for both UBOs.
	vk::MemoryRequirements mem_req;
	dev.getBufferMemoryRequirements(m_easu_ubo, &mem_req);
	vk::MemoryAllocateInfo mem_alloc {};
	mem_alloc.allocationSize  = mem_req.size * 2; // both UBOs in one allocation
	mem_alloc.memoryTypeIndex = 0;
	{
		auto props = m_gfx->GetPhysicalDeviceMemoryProperties();
		for (uint32_t i = 0; i < props.memoryTypeCount; i++) {
			if ((mem_req.memoryTypeBits & (1u << i)) &&
			    (props.memoryTypes[i].propertyFlags &
			     (vk::MemoryPropertyFlagBits::eHostVisible |
			      vk::MemoryPropertyFlagBits::eHostCoherent))) {
				mem_alloc.memoryTypeIndex = i;
				break;
			}
		}
	}
	result = dev.allocateMemory(&mem_alloc, nullptr, &m_easu_ubo_mem);
	if (result != vk::Result::eSuccess) return false;
	m_rcas_ubo_mem = m_easu_ubo_mem; // shared allocation

	dev.bindBufferMemory(m_easu_ubo, m_easu_ubo_mem, 0);
	dev.bindBufferMemory(m_rcas_ubo, m_easu_ubo_mem, mem_req.size);

	return true;
}

bool FsrUpscaler::EnsureIntermediate(uint32_t width, uint32_t height) {
	if (m_intermediate.width == width && m_intermediate.height == height) {
		return true;
	}
	auto dev = m_gfx->device;

	// Destroy old intermediate.
	if (m_intermediate.image != nullptr) {
		if (m_intermediate.view != nullptr) dev.destroyImageView(m_intermediate.view, nullptr);
		dev.destroyImage(m_intermediate.image, nullptr);
		dev.freeMemory(m_intermediate.memory, nullptr);
		m_intermediate = {};
	}

	// Create RGBA16F image for high-precision intermediate.
	vk::ImageCreateInfo img_info {};
	img_info.imageType   = vk::ImageType::e2D;
	img_info.format      = vk::Format::eR16G16B16A16Sfloat;
	img_info.extent      = vk::Extent3D {width, height, 1};
	img_info.mipLevels   = 1;
	img_info.arrayLayers = 1;
	img_info.samples     = vk::SampleCountFlagBits::e1;
	img_info.tiling      = vk::ImageTiling::eOptimal;
	img_info.usage       = vk::ImageUsageFlagBits::eStorage |
	                       vk::ImageUsageFlagBits::eSampled;
	img_info.sharingMode = vk::SharingMode::eExclusive;
	img_info.initialLayout = vk::ImageLayout::eUndefined;
	auto result = dev.createImage(&img_info, nullptr, &m_intermediate.image);
	if (result != vk::Result::eSuccess) return false;

	// Allocate memory.
	vk::MemoryRequirements mem_req;
	dev.getImageMemoryRequirements(m_intermediate.image, &mem_req);
	vk::MemoryAllocateInfo mem_alloc {};
	mem_alloc.allocationSize = mem_req.size;
	{
		auto props = m_gfx->GetPhysicalDeviceMemoryProperties();
		for (uint32_t i = 0; i < props.memoryTypeCount; i++) {
			if ((mem_req.memoryTypeBits & (1u << i)) &&
			    (props.memoryTypes[i].propertyFlags & vk::MemoryPropertyFlagBits::eDeviceLocal)) {
				mem_alloc.memoryTypeIndex = i;
				break;
			}
		}
	}
	result = dev.allocateMemory(&mem_alloc, nullptr, &m_intermediate.memory);
	if (result != vk::Result::eSuccess) return false;
	dev.bindImageMemory(m_intermediate.image, m_intermediate.memory, 0);

	// Create image view.
	vk::ImageViewCreateInfo view_info {};
	view_info.image            = m_intermediate.image;
	view_info.viewType         = vk::ImageViewType::e2D;
	view_info.format           = vk::Format::eR16G16B16A16Sfloat;
	view_info.subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
	result = dev.createImageView(&view_info, nullptr, &m_intermediate.view);
	if (result != vk::Result::eSuccess) return false;

	m_intermediate.width  = width;
	m_intermediate.height = height;
	return true;
}

void FsrUpscaler::Dispatch(vk::CommandBuffer cmd, VulkanImage& source, vk::Image dest,
                           vk::Format dest_format,
                           uint32_t src_w, uint32_t src_h,
                           uint32_t dst_w, uint32_t dst_h,
                           float sharpness) {
	if (!m_ready) return;
	auto dev = m_gfx->device;

	if (!EnsureIntermediate(dst_w, dst_h)) return;

	// ── Update UBOs ──────────────────────────────────────────────
	void* mapped = nullptr;
	dev.mapMemory(m_easu_ubo_mem, 0, VK_WHOLE_SIZE, vk::MemoryMapFlags {}, &mapped);

	// EASU UBO at offset 0.
	{
		auto* ubo   = static_cast<EasuUbo*>(mapped);
		ubo->src_size[0]  = static_cast<float>(src_w);
		ubo->src_size[1]  = static_cast<float>(src_h);
		ubo->dst_size[0]  = static_cast<float>(dst_w);
		ubo->dst_size[1]  = static_cast<float>(dst_h);
		ubo->src_pixel[0] = 1.0f / static_cast<float>(src_w);
		ubo->src_pixel[1] = 1.0f / static_cast<float>(src_h);
		ubo->dst_pixel[0] = 1.0f / static_cast<float>(dst_w);
		ubo->dst_pixel[1] = 1.0f / static_cast<float>(dst_h);
		ubo->scale[0]     = static_cast<float>(src_w) / static_cast<float>(dst_w);
		ubo->scale[1]     = static_cast<float>(src_h) / static_cast<float>(dst_h);
	}

	// RCAS UBO at offset = aligned EASU size.
	vk::MemoryRequirements mem_req;
	dev.getBufferMemoryRequirements(m_easu_ubo, &mem_req);
	{
		auto* ubo = reinterpret_cast<RcasUbo*>(static_cast<uint8_t*>(mapped) + mem_req.size);
		ubo->src_size[0]  = static_cast<float>(dst_w);
		ubo->src_size[1]  = static_cast<float>(dst_h);
		ubo->src_pixel[0] = 1.0f / static_cast<float>(dst_w);
		ubo->src_pixel[1] = 1.0f / static_cast<float>(dst_h);
		ubo->sharpness    = sharpness;
	}
	dev.unmapMemory(m_easu_ubo_mem);

	// ── Create source image view (for EASU input) ────────────────
	vk::ImageViewCreateInfo src_view_info {};
	src_view_info.image            = source.image;
	src_view_info.viewType         = vk::ImageViewType::e2D;
	src_view_info.format           = source.format;
	src_view_info.subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
	vk::ImageView src_view;
	if (dev.createImageView(&src_view_info, nullptr, &src_view) != vk::Result::eSuccess) return;

	// Create dest image view (for RCAS output → swapchain).
	vk::ImageViewCreateInfo dst_view_info {};
	dst_view_info.image            = dest;
	dst_view_info.viewType         = vk::ImageViewType::e2D;
	dst_view_info.format           = dest_format;
	dst_view_info.subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
	vk::ImageView dst_view;
	if (dev.createImageView(&dst_view_info, nullptr, &dst_view) != vk::Result::eSuccess) {
		dev.destroyImageView(src_view, nullptr);
		return;
	}

	// ── Transition images ────────────────────────────────────────
	// Source: eTransferSrcOptimal → eShaderReadOnlyOptimal (for compute read).
	// Intermediate: eUndefined → eGeneral (for compute write).
	// Dest: already eTransferDstOptimal (set by caller).
	{
		std::array<vk::ImageMemoryBarrier, 2> barriers {};

		barriers[0].sType               = vk::StructureType::eImageMemoryBarrier;
		barriers[0].srcAccessMask       = vk::AccessFlagBits::eTransferRead;
		barriers[0].dstAccessMask       = vk::AccessFlagBits::eShaderRead;
		barriers[0].oldLayout           = vk::ImageLayout::eTransferSrcOptimal;
		barriers[0].newLayout           = vk::ImageLayout::eShaderReadOnlyOptimal;
		barriers[0].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[0].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[0].image               = source.image;
		barriers[0].subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};

		barriers[1].sType               = vk::StructureType::eImageMemoryBarrier;
		barriers[1].dstAccessMask       = vk::AccessFlagBits::eShaderWrite;
		barriers[1].oldLayout           = vk::ImageLayout::eUndefined;
		barriers[1].newLayout           = vk::ImageLayout::eGeneral;
		barriers[1].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[1].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[1].image               = m_intermediate.image;
		barriers[1].subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};

		cmd.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer,
		                    vk::PipelineStageFlagBits::eComputeShader,
		                    vk::DependencyFlags {}, 0, nullptr, 0, nullptr,
		                    static_cast<uint32_t>(barriers.size()), barriers.data());
	}

	// ── Update EASU descriptor set ───────────────────────────────
	{
		vk::DescriptorImageInfo sampler_info {};
		sampler_info.sampler     = m_linear_sampler;
		sampler_info.imageView   = src_view;
		sampler_info.imageLayout = vk::ImageLayout::eShaderReadOnlyOptimal;

		vk::DescriptorImageInfo storage_info {};
		storage_info.imageView   = m_intermediate.view;
		storage_info.imageLayout = vk::ImageLayout::eGeneral;

		vk::DescriptorBufferInfo ubo_info {};
		ubo_info.buffer = m_easu_ubo;
		ubo_info.range  = VK_WHOLE_SIZE;

		std::array<vk::WriteDescriptorSet, 3> writes {};
		writes[0].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[0].dstSet          = m_easu_ds;
		writes[0].dstBinding      = 0;
		writes[0].descriptorCount = 1;
		writes[0].descriptorType  = vk::DescriptorType::eCombinedImageSampler;
		writes[0].pImageInfo      = &sampler_info;
		writes[1].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[1].dstSet          = m_easu_ds;
		writes[1].dstBinding      = 1;
		writes[1].descriptorCount = 1;
		writes[1].descriptorType  = vk::DescriptorType::eStorageImage;
		writes[1].pImageInfo      = &storage_info;
		writes[2].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[2].dstSet          = m_easu_ds;
		writes[2].dstBinding      = 2;
		writes[2].descriptorCount = 1;
		writes[2].descriptorType  = vk::DescriptorType::eUniformBuffer;
		writes[2].pBufferInfo     = &ubo_info;

		dev.updateDescriptorSets(static_cast<uint32_t>(writes.size()), writes.data(), 0, nullptr);
	}

	// ── Dispatch EASU ────────────────────────────────────────────
	cmd.bindPipeline(vk::PipelineBindPoint::eCompute, m_easu_pipeline);
	cmd.bindDescriptorSets(vk::PipelineBindPoint::eCompute, m_pipeline_layout,
	                       0, 1, &m_easu_ds, 0, nullptr);
	{
		uint32_t groups_x = (dst_w + 63) / 64;
		uint32_t groups_y = dst_h;
		cmd.dispatch(groups_x, groups_y, 1);
	}

	// ── Barrier: EASU write complete → RCAS read ─────────────────
	{
		vk::ImageMemoryBarrier barrier {};
		barrier.sType               = vk::StructureType::eImageMemoryBarrier;
		barrier.srcAccessMask       = vk::AccessFlagBits::eShaderWrite;
		barrier.dstAccessMask       = vk::AccessFlagBits::eShaderRead;
		barrier.oldLayout           = vk::ImageLayout::eGeneral;
		barrier.newLayout           = vk::ImageLayout::eGeneral;
		barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.image               = m_intermediate.image;
		barrier.subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
		cmd.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader,
		                    vk::PipelineStageFlagBits::eComputeShader,
		                    vk::DependencyFlags {}, 0, nullptr, 0, nullptr, 1, &barrier);
	}

	// ── Transition dest to eGeneral for RCAS write ───────────────
	{
		vk::ImageMemoryBarrier barrier {};
		barrier.sType               = vk::StructureType::eImageMemoryBarrier;
		barrier.srcAccessMask       = vk::AccessFlagBits::eTransferWrite;
		barrier.dstAccessMask       = vk::AccessFlagBits::eShaderWrite;
		barrier.oldLayout           = vk::ImageLayout::eTransferDstOptimal;
		barrier.newLayout           = vk::ImageLayout::eGeneral;
		barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.image               = dest;
		barrier.subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
		cmd.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer,
		                    vk::PipelineStageFlagBits::eComputeShader,
		                    vk::DependencyFlags {}, 0, nullptr, 0, nullptr, 1, &barrier);
	}

	// ── Update RCAS descriptor set ───────────────────────────────
	{
		vk::DescriptorImageInfo sampler_info {};
		sampler_info.sampler     = m_linear_sampler;
		sampler_info.imageView   = m_intermediate.view;
		sampler_info.imageLayout = vk::ImageLayout::eGeneral;

		vk::DescriptorImageInfo storage_info {};
		storage_info.imageView   = dst_view;
		storage_info.imageLayout = vk::ImageLayout::eGeneral;

		vk::DescriptorBufferInfo ubo_info {};
		ubo_info.buffer = m_rcas_ubo;
		ubo_info.range  = VK_WHOLE_SIZE;

		std::array<vk::WriteDescriptorSet, 3> writes {};
		writes[0].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[0].dstSet          = m_rcas_ds;
		writes[0].dstBinding      = 0;
		writes[0].descriptorCount = 1;
		writes[0].descriptorType  = vk::DescriptorType::eCombinedImageSampler;
		writes[0].pImageInfo      = &sampler_info;
		writes[1].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[1].dstSet          = m_rcas_ds;
		writes[1].dstBinding      = 1;
		writes[1].descriptorCount = 1;
		writes[1].descriptorType  = vk::DescriptorType::eStorageImage;
		writes[1].pImageInfo      = &storage_info;
		writes[2].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[2].dstSet          = m_rcas_ds;
		writes[2].dstBinding      = 2;
		writes[2].descriptorCount = 1;
		writes[2].descriptorType  = vk::DescriptorType::eUniformBuffer;
		writes[2].pBufferInfo     = &ubo_info;

		dev.updateDescriptorSets(static_cast<uint32_t>(writes.size()), writes.data(), 0, nullptr);
	}

	// ── Dispatch RCAS ────────────────────────────────────────────
	cmd.bindPipeline(vk::PipelineBindPoint::eCompute, m_rcas_pipeline);
	cmd.bindDescriptorSets(vk::PipelineBindPoint::eCompute, m_pipeline_layout,
	                       0, 1, &m_rcas_ds, 0, nullptr);
	{
		uint32_t groups_x = (dst_w + 63) / 64;
		uint32_t groups_y = dst_h;
		cmd.dispatch(groups_x, groups_y, 1);
	}

	// ── Transition dest: eGeneral → ePresentSrcKHR ───────────────
	// Also transition source back to eTransferSrcOptimal (caller expects it).
	{
		std::array<vk::ImageMemoryBarrier, 2> barriers {};

		barriers[0].sType               = vk::StructureType::eImageMemoryBarrier;
		barriers[0].srcAccessMask       = vk::AccessFlagBits::eShaderWrite;
		barriers[0].dstAccessMask       = vk::AccessFlagBits::eMemoryRead;
		barriers[0].oldLayout           = vk::ImageLayout::eGeneral;
		barriers[0].newLayout           = vk::ImageLayout::ePresentSrcKHR;
		barriers[0].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[0].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[0].image               = dest;
		barriers[0].subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};

		barriers[1].sType               = vk::StructureType::eImageMemoryBarrier;
		barriers[1].srcAccessMask       = vk::AccessFlagBits::eShaderRead;
		barriers[1].dstAccessMask       = vk::AccessFlagBits::eTransferRead;
		barriers[1].oldLayout           = vk::ImageLayout::eShaderReadOnlyOptimal;
		barriers[1].newLayout           = vk::ImageLayout::eTransferSrcOptimal;
		barriers[1].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[1].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[1].image               = source.image;
		barriers[1].subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};

		cmd.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader,
		                    vk::PipelineStageFlagBits::eAllCommands,
		                    vk::DependencyFlagBits::eByRegion, 0, nullptr, 0, nullptr,
		                    static_cast<uint32_t>(barriers.size()), barriers.data());
	}

	// Clean up per-frame views.
	dev.destroyImageView(src_view, nullptr);
	dev.destroyImageView(dst_view, nullptr);
}

} // namespace Libs::Graphics
