// SPDX-FileCopyrightText: Copyright 2024 KytyPlus
// SPDX-License-Identifier: MIT
//
// FSR-inspired spatial upscaler: EASU + RCAS two-pass compute pipeline.

#include "graphics/presentation/fsrUpscaler.h"

#include "common/assert.h"
#include "graphics/host_gpu/graphicContext.h"

#include <algorithm>

// Embedded SPIR-V shaders (generated by CMake from .comp sources).
#include "fsr_shaders/fsr_easu_spv.h"
#include "fsr_shaders/fsr_rcas_spv.h"

namespace Libs::Graphics {

// UBO layout matching the GLSL std140 blocks.
struct EasuUbo {
	float src_size[2];
	float dst_size[2];
	float src_pixel[2];
	float dst_pixel[2];
	float scale[2];
	float pad0[2];
};

struct RcasUbo {
	float src_size[2];
	float src_pixel[2];
	float sharpness;
	float pad0;
	float pad1;
	float pad2;
};

namespace {
vk::DeviceSize AlignUp(vk::DeviceSize value, vk::DeviceSize alignment) {
	if (alignment <= 1) {
		return value;
	}
	return (value + alignment - 1) & ~(alignment - 1);
}
} // namespace

FsrUpscaler::~FsrUpscaler() {
	Destroy();
}

bool FsrUpscaler::Create(VulkanInstance& gfx) {
	m_gfx = &gfx;

	// Sampler: linear filtering, clamp-to-edge.
	vk::SamplerCreateInfo sampler_info {};
	sampler_info.magFilter    = vk::Filter::eLinear;
	sampler_info.minFilter    = vk::Filter::eLinear;
	sampler_info.mipmapMode   = vk::SamplerMipmapMode::eNearest;
	sampler_info.addressModeU = vk::SamplerAddressMode::eClampToEdge;
	sampler_info.addressModeV = vk::SamplerAddressMode::eClampToEdge;
	sampler_info.addressModeW = vk::SamplerAddressMode::eClampToEdge;
	sampler_info.maxLod       = 0.0f;
	auto result = gfx.device.createSampler(&sampler_info, nullptr, &m_linear_sampler);
	if (result != vk::Result::eSuccess) {
		LOGF("FsrUpscaler: failed to create sampler\n");
		return false;
	}

	if (!CreatePipelines()) return false;
	if (!CreateDescriptorResources()) return false;

	m_ready = true;
	LOGF("FsrUpscaler: initialised (EASU + RCAS compute pipelines ready)\n");
	return true;
}

void FsrUpscaler::Destroy() {
	if (m_gfx == nullptr) return;
	auto dev = m_gfx->device;

	DestroyIntermediate(m_intermediate);
	DestroyIntermediate(m_result);
	if (m_dst_view != nullptr) { dev.destroyImageView(m_dst_view, nullptr); m_dst_view = nullptr; }
	for (auto& [img, view] : m_src_views) {
		if (view != nullptr) dev.destroyImageView(view, nullptr);
	}
	m_src_views.clear();
	if (m_easu_ubo != nullptr) {
		dev.destroyBuffer(m_easu_ubo, nullptr);
		dev.freeMemory(m_easu_ubo_mem, nullptr);
		m_easu_ubo = nullptr;
	}
	if (m_rcas_ubo != nullptr) {
		dev.destroyBuffer(m_rcas_ubo, nullptr);
		dev.freeMemory(m_rcas_ubo_mem, nullptr);
		m_rcas_ubo = nullptr;
	}
	if (m_desc_pool != nullptr) {
		dev.destroyDescriptorPool(m_desc_pool, nullptr);
		m_desc_pool = nullptr;
	}
	if (m_easu_pipeline != nullptr) { dev.destroyPipeline(m_easu_pipeline, nullptr); m_easu_pipeline = nullptr; }
	if (m_rcas_pipeline != nullptr) { dev.destroyPipeline(m_rcas_pipeline, nullptr); m_rcas_pipeline = nullptr; }
	if (m_pipeline_layout != nullptr) { dev.destroyPipelineLayout(m_pipeline_layout, nullptr); m_pipeline_layout = nullptr; }
	if (m_ds_layout != nullptr) { dev.destroyDescriptorSetLayout(m_ds_layout, nullptr); m_ds_layout = nullptr; }
	if (m_linear_sampler != nullptr) { dev.destroySampler(m_linear_sampler, nullptr); m_linear_sampler = nullptr; }
	m_gfx   = nullptr;
	m_ready = false;
}

bool FsrUpscaler::CreatePipelines() {
	auto dev = m_gfx->device;

	// Descriptor set layout: 3 bindings (sampler, storage image, UBO).
	std::array<vk::DescriptorSetLayoutBinding, 3> bindings {};
	bindings[0].binding            = 0;
	bindings[0].descriptorType     = vk::DescriptorType::eCombinedImageSampler;
	bindings[0].descriptorCount    = 1;
	bindings[0].stageFlags         = vk::ShaderStageFlagBits::eCompute;
	bindings[1].binding            = 1;
	bindings[1].descriptorType     = vk::DescriptorType::eStorageImage;
	bindings[1].descriptorCount    = 1;
	bindings[1].stageFlags         = vk::ShaderStageFlagBits::eCompute;
	bindings[2].binding            = 2;
	bindings[2].descriptorType     = vk::DescriptorType::eUniformBuffer;
	bindings[2].descriptorCount    = 1;
	bindings[2].stageFlags         = vk::ShaderStageFlagBits::eCompute;

	vk::DescriptorSetLayoutCreateInfo ds_layout_info {};
	ds_layout_info.bindingCount = static_cast<uint32_t>(bindings.size());
	ds_layout_info.pBindings    = bindings.data();
	auto result = dev.createDescriptorSetLayout(&ds_layout_info, nullptr, &m_ds_layout);
	if (result != vk::Result::eSuccess) return false;

	// Pipeline layout.
	vk::PipelineLayoutCreateInfo pl_info {};
	pl_info.setLayoutCount = 1;
	pl_info.pSetLayouts    = &m_ds_layout;
	result = dev.createPipelineLayout(&pl_info, nullptr, &m_pipeline_layout);
	if (result != vk::Result::eSuccess) return false;

	// EASU compute pipeline.
	{
		vk::ShaderModuleCreateInfo sm_info {};
		sm_info.codeSize = sizeof(FSR_EASU_SPV);
		sm_info.pCode    = FSR_EASU_SPV;
		vk::ShaderModule module;
		result = dev.createShaderModule(&sm_info, nullptr, &module);
		if (result != vk::Result::eSuccess) return false;

		vk::PipelineShaderStageCreateInfo stage {};
		stage.stage  = vk::ShaderStageFlagBits::eCompute;
		stage.module = module;
		stage.pName  = "main";

		vk::ComputePipelineCreateInfo cp {};
		cp.stage  = stage;
		cp.layout = m_pipeline_layout;
		result = dev.createComputePipelines(nullptr, 1, &cp, nullptr, &m_easu_pipeline);
		dev.destroyShaderModule(module, nullptr);
		if (result != vk::Result::eSuccess) return false;
	}

	// RCAS compute pipeline.
	{
		vk::ShaderModuleCreateInfo sm_info {};
		sm_info.codeSize = sizeof(FSR_RCAS_SPV);
		sm_info.pCode    = FSR_RCAS_SPV;
		vk::ShaderModule module;
		result = dev.createShaderModule(&sm_info, nullptr, &module);
		if (result != vk::Result::eSuccess) return false;

		vk::PipelineShaderStageCreateInfo stage {};
		stage.stage  = vk::ShaderStageFlagBits::eCompute;
		stage.module = module;
		stage.pName  = "main";

		vk::ComputePipelineCreateInfo cp {};
		cp.stage  = stage;
		cp.layout = m_pipeline_layout;
		result = dev.createComputePipelines(nullptr, 1, &cp, nullptr, &m_rcas_pipeline);
		dev.destroyShaderModule(module, nullptr);
		if (result != vk::Result::eSuccess) return false;
	}

	return true;
}

bool FsrUpscaler::CreateDescriptorResources() {
	auto dev = m_gfx->device;

	// Descriptor pool: 2 sets, each with 1 sampler + 1 storage image + 1 UBO.
	std::array<vk::DescriptorPoolSize, 3> pool_sizes {};
	pool_sizes[0].type            = vk::DescriptorType::eCombinedImageSampler;
	pool_sizes[0].descriptorCount = 2;
	pool_sizes[1].type            = vk::DescriptorType::eStorageImage;
	pool_sizes[1].descriptorCount = 2;
	pool_sizes[2].type            = vk::DescriptorType::eUniformBuffer;
	pool_sizes[2].descriptorCount = 2;

	vk::DescriptorPoolCreateInfo pool_info {};
	pool_info.maxSets       = 2;
	pool_info.poolSizeCount = static_cast<uint32_t>(pool_sizes.size());
	pool_info.pPoolSizes    = pool_sizes.data();
	auto result = dev.createDescriptorPool(&pool_info, nullptr, &m_desc_pool);
	if (result != vk::Result::eSuccess) return false;

	// Allocate two descriptor sets.
	vk::DescriptorSetAllocateInfo alloc_info {};
	alloc_info.descriptorPool     = m_desc_pool;
	alloc_info.descriptorSetCount = 1;
	alloc_info.pSetLayouts        = &m_ds_layout;
	result = dev.allocateDescriptorSets(&alloc_info, &m_easu_ds);
	if (result != vk::Result::eSuccess) return false;
	result = dev.allocateDescriptorSets(&alloc_info, &m_rcas_ds);
	if (result != vk::Result::eSuccess) return false;

	// UBO layout is a single 64-byte std140 block shared by both passes. The RCAS
	// UBO shares the same host-visible allocation with EASU, offset by an
	// alignment that satisfies both the UBO and a host-coherent memory mapping.
	constexpr vk::DeviceSize ubo_size = 64; // padded to 64 bytes, both UBOs fit.

	// The descriptor offset into the shared allocation must be a multiple of the
	// device's uniform-buffer offset alignment. mem_req.size (the alignment of a
	// single 64-byte buffer) is NOT a correct substitute: it is commonly smaller
	// than minUniformBufferOffsetAlignment (e.g. 64 vs 256 on many discrete GPUs).
	const vk::DeviceSize ubo_alignment =
	    std::max<vk::DeviceSize>(m_gfx->GetPhysicalDeviceProperties().limits
	                                  .minUniformBufferOffsetAlignment,
	                             ubo_size);
	const vk::DeviceSize rcas_offset = AlignUp(ubo_size, ubo_alignment);
	m_rcas_ubo_offset                = rcas_offset;
	const vk::DeviceSize alloc_size  = rcas_offset + ubo_size;

	for (auto* buf_ptr: {&m_easu_ubo, &m_rcas_ubo}) {
		vk::BufferCreateInfo buf_info {};
		buf_info.size        = ubo_size;
		buf_info.usage       = vk::BufferUsageFlagBits::eUniformBuffer;
		buf_info.sharingMode = vk::SharingMode::eExclusive;
		result = dev.createBuffer(&buf_info, nullptr, buf_ptr);
		if (result != vk::Result::eSuccess) return false;
	}

	// Allocate host-visible memory for both UBOs.
	vk::MemoryRequirements mem_req;
	dev.getBufferMemoryRequirements(m_easu_ubo, &mem_req);
	if (rcas_offset + ubo_size < mem_req.size * 2) {
		// Keep the allocation large enough for the aligned layout.
		mem_req.size = AlignUp(mem_req.size, ubo_alignment) * 2;
	}
	vk::MemoryAllocateInfo mem_alloc {};
	mem_alloc.allocationSize  = std::max(alloc_size, mem_req.size);
	mem_alloc.memoryTypeIndex = 0;

	bool found_host_memory_type = false;
	{
		auto props = m_gfx->GetPhysicalDeviceMemoryProperties();
		for (uint32_t i = 0; i < props.memoryTypeCount; i++) {
			if ((mem_req.memoryTypeBits & (1u << i)) &&
			    (props.memoryTypes[i].propertyFlags &
			     (vk::MemoryPropertyFlagBits::eHostVisible |
			      vk::MemoryPropertyFlagBits::eHostCoherent))) {
				mem_alloc.memoryTypeIndex = i;
				found_host_memory_type    = true;
				break;
			}
		}
	}
	if (!found_host_memory_type) {
		LOGF("FsrUpscaler: no host-visible coherent memory type for UBOs\n");
		return false;
	}
	result = dev.allocateMemory(&mem_alloc, nullptr, &m_easu_ubo_mem);
	if (result != vk::Result::eSuccess) return false;
	m_rcas_ubo_mem = m_easu_ubo_mem; // shared allocation

	dev.bindBufferMemory(m_easu_ubo, m_easu_ubo_mem, 0);
	dev.bindBufferMemory(m_rcas_ubo, m_easu_ubo_mem, m_rcas_ubo_offset);

	return true;
}

void FsrUpscaler::DestroyIntermediate(IntermediateImage& img) {
	if (img.image == nullptr) {
		img = {};
		return;
	}
	auto dev = m_gfx->device;
	if (img.view != nullptr) dev.destroyImageView(img.view, nullptr);
	dev.destroyImage(img.image, nullptr);
	dev.freeMemory(img.memory, nullptr);
	img = {};
}

bool FsrUpscaler::EnsureIntermediate(uint32_t width, uint32_t height) {
	if (m_intermediate.width == width && m_intermediate.height == height) {
		return true;
	}
	auto dev = m_gfx->device;

	// Destroy old intermediate.
	DestroyIntermediate(m_intermediate);

	// Create RGBA16F image for high-precision intermediate.
	vk::ImageCreateInfo img_info {};
	img_info.imageType   = vk::ImageType::e2D;
	img_info.format      = vk::Format::eR16G16B16A16Sfloat;
	img_info.extent      = vk::Extent3D {width, height, 1};
	img_info.mipLevels   = 1;
	img_info.arrayLayers = 1;
	img_info.samples     = vk::SampleCountFlagBits::e1;
	img_info.tiling      = vk::ImageTiling::eOptimal;
	img_info.usage       = vk::ImageUsageFlagBits::eStorage |
	                       vk::ImageUsageFlagBits::eSampled;
	img_info.sharingMode = vk::SharingMode::eExclusive;
	img_info.initialLayout = vk::ImageLayout::eUndefined;
	auto result = dev.createImage(&img_info, nullptr, &m_intermediate.image);
	if (result != vk::Result::eSuccess) return false;

	// Allocate memory.
	vk::MemoryRequirements mem_req;
	dev.getImageMemoryRequirements(m_intermediate.image, &mem_req);
	vk::MemoryAllocateInfo mem_alloc {};
	mem_alloc.allocationSize = mem_req.size;
	{
		auto props = m_gfx->GetPhysicalDeviceMemoryProperties();
		for (uint32_t i = 0; i < props.memoryTypeCount; i++) {
			if ((mem_req.memoryTypeBits & (1u << i)) &&
			    (props.memoryTypes[i].propertyFlags & vk::MemoryPropertyFlagBits::eDeviceLocal)) {
				mem_alloc.memoryTypeIndex = i;
				break;
			}
		}
	}
	result = dev.allocateMemory(&mem_alloc, nullptr, &m_intermediate.memory);
	if (result != vk::Result::eSuccess) return false;
	dev.bindImageMemory(m_intermediate.image, m_intermediate.memory, 0);

	// Create image view.
	vk::ImageViewCreateInfo view_info {};
	view_info.image            = m_intermediate.image;
	view_info.viewType         = vk::ImageViewType::e2D;
	view_info.format           = vk::Format::eR16G16B16A16Sfloat;
	view_info.subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
	result = dev.createImageView(&view_info, nullptr, &m_intermediate.view);
	if (result != vk::Result::eSuccess) return false;

	m_intermediate.width  = width;
	m_intermediate.height = height;
	return true;
}

bool FsrUpscaler::EnsureResult(uint32_t width, uint32_t height) {
	if (m_result.width == width && m_result.height == height) {
		return true;
	}
	auto dev = m_gfx->device;

	// The cached dest view references the old result image; drop it before the
	// image is destroyed. (Resize is a rare, swapchain-recreating event, so the
	// prior frame's command buffer is already retired here.)
	if (m_dst_view != nullptr) {
		dev.destroyImageView(m_dst_view, nullptr);
		m_dst_view = nullptr;
	}

	DestroyIntermediate(m_result);

	// R8G8B8A8Unorm result image: RCAS writes here (matching the shader's rgba8
	// storage qualifier), then a blit copies it to the swapchain image. Both are
	// in the 8-bit UNORM format-compatibility class, so the blit is valid and
	// also handles B8G8R8A8 channel reordering on the swapchain side.
	vk::ImageCreateInfo img_info {};
	img_info.imageType   = vk::ImageType::e2D;
	img_info.format      = vk::Format::eR8G8B8A8Unorm;
	img_info.extent      = vk::Extent3D {width, height, 1};
	img_info.mipLevels   = 1;
	img_info.arrayLayers = 1;
	img_info.samples     = vk::SampleCountFlagBits::e1;
	img_info.tiling      = vk::ImageTiling::eOptimal;
	img_info.usage       = vk::ImageUsageFlagBits::eStorage |
	                       vk::ImageUsageFlagBits::eSampled |
	                       vk::ImageUsageFlagBits::eTransferSrc;
	img_info.sharingMode = vk::SharingMode::eExclusive;
	img_info.initialLayout = vk::ImageLayout::eUndefined;
	auto result = dev.createImage(&img_info, nullptr, &m_result.image);
	if (result != vk::Result::eSuccess) return false;

	vk::MemoryRequirements mem_req;
	dev.getImageMemoryRequirements(m_result.image, &mem_req);
	vk::MemoryAllocateInfo mem_alloc {};
	mem_alloc.allocationSize = mem_req.size;
	{
		auto props = m_gfx->GetPhysicalDeviceMemoryProperties();
		for (uint32_t i = 0; i < props.memoryTypeCount; i++) {
			if ((mem_req.memoryTypeBits & (1u << i)) &&
			    (props.memoryTypes[i].propertyFlags & vk::MemoryPropertyFlagBits::eDeviceLocal)) {
				mem_alloc.memoryTypeIndex = i;
				break;
			}
		}
	}
	result = dev.allocateMemory(&mem_alloc, nullptr, &m_result.memory);
	if (result != vk::Result::eSuccess) return false;
	dev.bindImageMemory(m_result.image, m_result.memory, 0);

	vk::ImageViewCreateInfo view_info {};
	view_info.image            = m_result.image;
	view_info.viewType         = vk::ImageViewType::e2D;
	view_info.format           = vk::Format::eR8G8B8A8Unorm;
	view_info.subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
	result = dev.createImageView(&view_info, nullptr, &m_result.view);
	if (result != vk::Result::eSuccess) return false;

	m_result.width  = width;
	m_result.height = height;
	return true;
}

void FsrUpscaler::Dispatch(vk::CommandBuffer cmd, VulkanImage& source, vk::Image dest,
                           vk::Format dest_format,
                           uint32_t src_w, uint32_t src_h,
                           uint32_t dst_w, uint32_t dst_h,
                           float sharpness) {
	if (!m_ready) return;
	auto dev = m_gfx->device;

	// dest_format is retained for API compatibility; the result image is always
	// RGBA16F and the blit handles the format conversion to the swapchain.
	(void)dest_format;

	if (!EnsureIntermediate(dst_w, dst_h)) return;
	if (!EnsureResult(dst_w, dst_h)) return;

	// ── Update UBOs ──────────────────────────────────────────────
	void* mapped = nullptr;
	dev.mapMemory(m_easu_ubo_mem, 0, VK_WHOLE_SIZE, vk::MemoryMapFlags {}, &mapped);

	// EASU UBO at offset 0.
	{
		auto* ubo   = static_cast<EasuUbo*>(mapped);
		ubo->src_size[0]  = static_cast<float>(src_w);
		ubo->src_size[1]  = static_cast<float>(src_h);
		ubo->dst_size[0]  = static_cast<float>(dst_w);
		ubo->dst_size[1]  = static_cast<float>(dst_h);
		ubo->src_pixel[0] = 1.0f / static_cast<float>(src_w);
		ubo->src_pixel[1] = 1.0f / static_cast<float>(src_h);
		ubo->dst_pixel[0] = 1.0f / static_cast<float>(dst_w);
		ubo->dst_pixel[1] = 1.0f / static_cast<float>(dst_h);
		ubo->scale[0]     = static_cast<float>(src_w) / static_cast<float>(dst_w);
		ubo->scale[1]     = static_cast<float>(src_h) / static_cast<float>(dst_h);
	}

	// RCAS UBO at the aligned offset established at creation. This must match
	// the m_rcas_ubo_offset used by bindBufferMemory so the CPU-mapped address
	// lines up with the descriptor's view of the same bytes.
	{
		auto* ubo = reinterpret_cast<RcasUbo*>(static_cast<uint8_t*>(mapped) + m_rcas_ubo_offset);
		ubo->src_size[0]  = static_cast<float>(dst_w);
		ubo->src_size[1]  = static_cast<float>(dst_h);
		ubo->src_pixel[0] = 1.0f / static_cast<float>(dst_w);
		ubo->src_pixel[1] = 1.0f / static_cast<float>(dst_h);
		ubo->sharpness    = sharpness;
	}
	dev.unmapMemory(m_easu_ubo_mem);

	// ── Create source image view (for EASU input) ────────────────
	// Views are cached and reused across frames. They are destroyed only in
	// Destroy(), never here: the command buffer referencing them is submitted
	// asynchronously after Dispatch() returns, so destroying them now would be
	// a use-after-free on the GPU. The source image may change between frames
	// (guest framebuffer buffering), so views are cached per image handle.
	vk::ImageView src_view = nullptr;
	for (const auto& [img, view] : m_src_views) {
		if (img == source.image) {
			src_view = view;
			break;
		}
	}
	if (src_view == nullptr) {
		vk::ImageViewCreateInfo src_view_info {};
		src_view_info.image            = source.image;
		src_view_info.viewType         = vk::ImageViewType::e2D;
		src_view_info.format           = source.format;
		src_view_info.subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
		if (dev.createImageView(&src_view_info, nullptr, &src_view) != vk::Result::eSuccess) return;
		m_src_views.emplace_back(source.image, src_view);
	}

	// Create dest image view (for RCAS output → result image).
	if (m_dst_view == nullptr) {
		vk::ImageViewCreateInfo dst_view_info {};
		dst_view_info.image            = m_result.image;
		dst_view_info.viewType         = vk::ImageViewType::e2D;
		dst_view_info.format           = vk::Format::eR8G8B8A8Unorm;
		dst_view_info.subresourceRange = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
		if (dev.createImageView(&dst_view_info, nullptr, &m_dst_view) != vk::Result::eSuccess) return;
	}
	vk::ImageView dst_view = m_dst_view;

	// ── Transition images ────────────────────────────────────────
	// Source: eTransferSrcOptimal → eShaderReadOnlyOptimal (for compute read).
	// Intermediate: eUndefined → eGeneral (for compute write).
	// Result: eUndefined → eGeneral (for RCAS compute write).
	{
		std::array<vk::ImageMemoryBarrier, 3> barriers {};

		barriers[0].sType               = vk::StructureType::eImageMemoryBarrier;
		barriers[0].srcAccessMask       = vk::AccessFlagBits::eTransferRead;
		barriers[0].dstAccessMask       = vk::AccessFlagBits::eShaderRead;
		barriers[0].oldLayout           = vk::ImageLayout::eTransferSrcOptimal;
		barriers[0].newLayout           = vk::ImageLayout::eShaderReadOnlyOptimal;
		barriers[0].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[0].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[0].image               = source.image;
		barriers[0].subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};

		barriers[1].sType               = vk::StructureType::eImageMemoryBarrier;
		barriers[1].dstAccessMask       = vk::AccessFlagBits::eShaderWrite;
		barriers[1].oldLayout           = vk::ImageLayout::eUndefined;
		barriers[1].newLayout           = vk::ImageLayout::eGeneral;
		barriers[1].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[1].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[1].image               = m_intermediate.image;
		barriers[1].subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};

		barriers[2].sType               = vk::StructureType::eImageMemoryBarrier;
		barriers[2].dstAccessMask       = vk::AccessFlagBits::eShaderWrite;
		barriers[2].oldLayout           = vk::ImageLayout::eUndefined;
		barriers[2].newLayout           = vk::ImageLayout::eGeneral;
		barriers[2].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[2].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[2].image               = m_result.image;
		barriers[2].subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};

		cmd.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer,
		                    vk::PipelineStageFlagBits::eComputeShader,
		                    vk::DependencyFlags {}, 0, nullptr, 0, nullptr,
		                    static_cast<uint32_t>(barriers.size()), barriers.data());
	}

	// ── Update EASU descriptor set ───────────────────────────────
	{
		vk::DescriptorImageInfo sampler_info {};
		sampler_info.sampler     = m_linear_sampler;
		sampler_info.imageView   = src_view;
		sampler_info.imageLayout = vk::ImageLayout::eShaderReadOnlyOptimal;

		vk::DescriptorImageInfo storage_info {};
		storage_info.imageView   = m_intermediate.view;
		storage_info.imageLayout = vk::ImageLayout::eGeneral;

		vk::DescriptorBufferInfo ubo_info {};
		ubo_info.buffer = m_easu_ubo;
		ubo_info.range  = VK_WHOLE_SIZE;

		std::array<vk::WriteDescriptorSet, 3> writes {};
		writes[0].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[0].dstSet          = m_easu_ds;
		writes[0].dstBinding      = 0;
		writes[0].descriptorCount = 1;
		writes[0].descriptorType  = vk::DescriptorType::eCombinedImageSampler;
		writes[0].pImageInfo      = &sampler_info;
		writes[1].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[1].dstSet          = m_easu_ds;
		writes[1].dstBinding      = 1;
		writes[1].descriptorCount = 1;
		writes[1].descriptorType  = vk::DescriptorType::eStorageImage;
		writes[1].pImageInfo      = &storage_info;
		writes[2].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[2].dstSet          = m_easu_ds;
		writes[2].dstBinding      = 2;
		writes[2].descriptorCount = 1;
		writes[2].descriptorType  = vk::DescriptorType::eUniformBuffer;
		writes[2].pBufferInfo     = &ubo_info;

		dev.updateDescriptorSets(static_cast<uint32_t>(writes.size()), writes.data(), 0, nullptr);
	}

	// ── Dispatch EASU ────────────────────────────────────────────
	cmd.bindPipeline(vk::PipelineBindPoint::eCompute, m_easu_pipeline);
	cmd.bindDescriptorSets(vk::PipelineBindPoint::eCompute, m_pipeline_layout,
	                       0, 1, &m_easu_ds, 0, nullptr);
	{
		uint32_t groups_x = (dst_w + 63) / 64;
		uint32_t groups_y = dst_h;
		cmd.dispatch(groups_x, groups_y, 1);
	}

	// ── Barrier: EASU write complete → RCAS read ─────────────────
	{
		vk::ImageMemoryBarrier barrier {};
		barrier.sType               = vk::StructureType::eImageMemoryBarrier;
		barrier.srcAccessMask       = vk::AccessFlagBits::eShaderWrite;
		barrier.dstAccessMask       = vk::AccessFlagBits::eShaderRead;
		barrier.oldLayout           = vk::ImageLayout::eGeneral;
		barrier.newLayout           = vk::ImageLayout::eGeneral;
		barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.image               = m_intermediate.image;
		barrier.subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
		cmd.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader,
		                    vk::PipelineStageFlagBits::eComputeShader,
		                    vk::DependencyFlags {}, 0, nullptr, 0, nullptr, 1, &barrier);
	}

	// ── Update RCAS descriptor set ───────────────────────────────
	{
		vk::DescriptorImageInfo sampler_info {};
		sampler_info.sampler     = m_linear_sampler;
		sampler_info.imageView   = m_intermediate.view;
		sampler_info.imageLayout = vk::ImageLayout::eGeneral;

		vk::DescriptorImageInfo storage_info {};
		storage_info.imageView   = dst_view;
		storage_info.imageLayout = vk::ImageLayout::eGeneral;

		vk::DescriptorBufferInfo ubo_info {};
		ubo_info.buffer = m_rcas_ubo;
		ubo_info.range  = VK_WHOLE_SIZE;

		std::array<vk::WriteDescriptorSet, 3> writes {};
		writes[0].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[0].dstSet          = m_rcas_ds;
		writes[0].dstBinding      = 0;
		writes[0].descriptorCount = 1;
		writes[0].descriptorType  = vk::DescriptorType::eCombinedImageSampler;
		writes[0].pImageInfo      = &sampler_info;
		writes[1].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[1].dstSet          = m_rcas_ds;
		writes[1].dstBinding      = 1;
		writes[1].descriptorCount = 1;
		writes[1].descriptorType  = vk::DescriptorType::eStorageImage;
		writes[1].pImageInfo      = &storage_info;
		writes[2].sType           = vk::StructureType::eWriteDescriptorSet;
		writes[2].dstSet          = m_rcas_ds;
		writes[2].dstBinding      = 2;
		writes[2].descriptorCount = 1;
		writes[2].descriptorType  = vk::DescriptorType::eUniformBuffer;
		writes[2].pBufferInfo     = &ubo_info;

		dev.updateDescriptorSets(static_cast<uint32_t>(writes.size()), writes.data(), 0, nullptr);
	}

	// ── Dispatch RCAS ────────────────────────────────────────────
	cmd.bindPipeline(vk::PipelineBindPoint::eCompute, m_rcas_pipeline);
	cmd.bindDescriptorSets(vk::PipelineBindPoint::eCompute, m_pipeline_layout,
	                       0, 1, &m_rcas_ds, 0, nullptr);
	{
		uint32_t groups_x = (dst_w + 63) / 64;
		uint32_t groups_y = dst_h;
		cmd.dispatch(groups_x, groups_y, 1);
	}

	// ── Transition result: eGeneral → eTransferSrcOptimal (for blit) ──
	// Also transition source back to eTransferSrcOptimal (caller expects it).
	{
		std::array<vk::ImageMemoryBarrier, 2> barriers {};

		barriers[0].sType               = vk::StructureType::eImageMemoryBarrier;
		barriers[0].srcAccessMask       = vk::AccessFlagBits::eShaderWrite;
		barriers[0].dstAccessMask       = vk::AccessFlagBits::eTransferRead;
		barriers[0].oldLayout           = vk::ImageLayout::eGeneral;
		barriers[0].newLayout           = vk::ImageLayout::eTransferSrcOptimal;
		barriers[0].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[0].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[0].image               = m_result.image;
		barriers[0].subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};

		barriers[1].sType               = vk::StructureType::eImageMemoryBarrier;
		barriers[1].srcAccessMask       = vk::AccessFlagBits::eShaderRead;
		barriers[1].dstAccessMask       = vk::AccessFlagBits::eTransferRead;
		barriers[1].oldLayout           = vk::ImageLayout::eShaderReadOnlyOptimal;
		barriers[1].newLayout           = vk::ImageLayout::eTransferSrcOptimal;
		barriers[1].srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[1].dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barriers[1].image               = source.image;
		barriers[1].subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};

		cmd.pipelineBarrier(vk::PipelineStageFlagBits::eComputeShader,
		                    vk::PipelineStageFlagBits::eTransfer,
		                    vk::DependencyFlags {}, 0, nullptr, 0, nullptr,
		                    static_cast<uint32_t>(barriers.size()), barriers.data());
	}

	// ── Blit result (RGBA16F) → swapchain image (R8G8B8A8Unorm) ──
	// The swapchain image is already in eTransferDstOptimal (set by the caller).
	{
		vk::ImageBlit region {};
		region.srcSubresource.aspectMask     = vk::ImageAspectFlagBits::eColor;
		region.srcSubresource.mipLevel       = 0;
		region.srcSubresource.baseArrayLayer = 0;
		region.srcSubresource.layerCount     = 1;
		region.srcOffsets[1].x               = static_cast<int>(dst_w);
		region.srcOffsets[1].y               = static_cast<int>(dst_h);
		region.srcOffsets[1].z               = 1;
		region.dstSubresource.aspectMask     = vk::ImageAspectFlagBits::eColor;
		region.dstSubresource.mipLevel       = 0;
		region.dstSubresource.baseArrayLayer = 0;
		region.dstSubresource.layerCount     = 1;
		region.dstOffsets[1].x               = static_cast<int>(dst_w);
		region.dstOffsets[1].y               = static_cast<int>(dst_h);
		region.dstOffsets[1].z               = 1;
		cmd.blitImage(m_result.image, vk::ImageLayout::eTransferSrcOptimal,
		              dest, vk::ImageLayout::eTransferDstOptimal, 1, &region,
		              vk::Filter::eLinear);
	}

	// ── Transition dest: eTransferDstOptimal → ePresentSrcKHR ────
	{
		vk::ImageMemoryBarrier barrier {};
		barrier.sType               = vk::StructureType::eImageMemoryBarrier;
		barrier.srcAccessMask       = vk::AccessFlagBits::eTransferWrite;
		barrier.dstAccessMask       = vk::AccessFlagBits::eMemoryRead;
		barrier.oldLayout           = vk::ImageLayout::eTransferDstOptimal;
		barrier.newLayout           = vk::ImageLayout::ePresentSrcKHR;
		barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
		barrier.image               = dest;
		barrier.subresourceRange    = {vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1};
		cmd.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer,
		                    vk::PipelineStageFlagBits::eAllCommands,
		                    vk::DependencyFlagBits::eByRegion, 0, nullptr, 0, nullptr, 1, &barrier);
	}
}

} // namespace Libs::Graphics
