name: KytyPS5 Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.6.0
        with:
          version: 1.4.350.0
          cache: true
          stripdown: false  # Install full SDK

      - name: Install Swiftshader (CI fallback)
        run: |
          Invoke-WebRequest -Uri "https://github.com/google/swiftshader/releases/download/vulkan-1.3.290.0/swiftshader.zip" -OutFile "$env:RUNNER_TEMP\swiftshader.zip"
          Expand-Archive -Path "$env:RUNNER_TEMP\swiftshader.zip" -DestinationPath "$env:RUNNER_TEMP\swiftshader"
          Copy-Item -Path "$env:RUNNER_TEMP\swiftshader\vulkan-1.dll" -Destination "$env:GITHUB_WORKSPACE"

      - name: Configure CMake
        run: cmake -B _Build/windows -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: Build
        run: cmake --build _Build/windows --config Release